export enum DueDateEnum {
  DUE_DAYS_FDPG_CHECK = 'DUE_DAYS_FDPG_CHECK',
  DUE_DAYS_DATA_CORRUPT = 'DUE_DAYS_DATA_CORRUPT',
  DUE_DAYS_FINISHED_PROJECT = 'DUE_DAYS_FINISHED_PROJECT',
  DUE_DAYS_LOCATION_CHECK = 'DUE_DAYS_LOCATION_CHECK',
  DUE_DAYS_EXPECT_DATA_DELIVERY = 'DUE_DAYS_EXPECT_DATA_DELIVERY',
  DUE_DAYS_LOCATION_CONTRACTING = 'DUE_DAYS_LOCATION_CONTRACTING',
}

export interface Deadlines {
  [DueDateEnum.DUE_DAYS_FDPG_CHECK]: string | null
  [DueDateEnum.DUE_DAYS_DATA_CORRUPT]: string | null
  [DueDateEnum.DUE_DAYS_FINISHED_PROJECT]: string | null
  [DueDateEnum.DUE_DAYS_LOCATION_CHECK]: string | null
  [DueDateEnum.DUE_DAYS_EXPECT_DATA_DELIVERY]: string | null
  [DueDateEnum.DUE_DAYS_LOCATION_CONTRACTING]: string | null
}
